// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AudioService exposes native playback to the frontend when libmpv or libvlc is available.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pcmsink$0 from "../internal/pcmsink/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivatePrepared swaps the standby player into the primary slot.
 * When crossfadeSec > 0, volumes are ramped between the two players.
 */
export function ActivatePrepared(crossfadeSec: number): $CancellablePromise<void> {
    return $Call.ByID(953013766, crossfadeSec);
}

/**
 * Capabilities reports whether native playback can be used.
 */
export function Capabilities(): $CancellablePromise<$models.AudioCapabilities> {
    return $Call.ByID(3875120476).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearEnded resets the ended latch after the frontend handles track completion.
 */
export function ClearEnded(): $CancellablePromise<void> {
    return $Call.ByID(942362633);
}

/**
 * ClearPrepared discards any standby preparation.
 */
export function ClearPrepared(): $CancellablePromise<void> {
    return $Call.ByID(200961342);
}

/**
 * GetAudioOutputConfig returns the active immersive audio settings.
 */
export function GetAudioOutputConfig(): $CancellablePromise<$models.AudioOutputConfig> {
    return $Call.ByID(3464815815).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSinkStatus reports the health of each configured PCM output target.
 */
export function GetSinkStatus(): $CancellablePromise<pcmsink$0.SinkStatus[]> {
    return $Call.ByID(2925085311).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetState returns the current native playback state.
 */
export function GetState(): $CancellablePromise<$models.AudioPlaybackState> {
    return $Call.ByID(1554589411).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * HasPrepared reports whether the standby player is ready for the given URL.
 */
export function HasPrepared(url: string): $CancellablePromise<boolean> {
    return $Call.ByID(559132575, url);
}

/**
 * LoadURL opens a stream URL in the native player.
 */
export function LoadURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(4045180659, url);
}

/**
 * Pause pauses native playback.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(4138672340);
}

/**
 * Play starts or resumes native playback.
 */
export function Play(): $CancellablePromise<void> {
    return $Call.ByID(435081404);
}

/**
 * PrepareURL loads the next track into a standby player for gapless handoff.
 */
export function PrepareURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1375089162, url);
}

/**
 * Seek moves playback to the given time in seconds.
 */
export function Seek(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(947751018, seconds);
}

/**
 * SetAudioOutputConfig applies immersive audio settings to native players.
 * Mode or target changes recreate the backend so mpv and VLC start options
 * take effect.
 */
export function SetAudioOutputConfig(cfg: $models.AudioOutputConfig): $CancellablePromise<void> {
    return $Call.ByID(478147811, cfg);
}

/**
 * SetPreferredBackend switches the native backend. Pass "auto", "mpv", or "vlc".
 */
export function SetPreferredBackend(preferred: string): $CancellablePromise<void> {
    return $Call.ByID(33484729, preferred);
}

/**
 * SetVolume sets native output volume from 0 to 1.
 */
export function SetVolume(volume: number): $CancellablePromise<void> {
    return $Call.ByID(331224420, volume);
}

/**
 * Shutdown closes the native backend.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2594506148);
}

// Private type creation functions
const $$createType0 = $models.AudioCapabilities.createFrom;
const $$createType1 = $models.AudioOutputConfig.createFrom;
const $$createType2 = pcmsink$0.SinkStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.AudioPlaybackState.createFrom;
