// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetGraphicsEnvironment(): $CancellablePromise<$models.GraphicsEnvironment> {
    return $Call.ByID(3872180318).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPlaybackState(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(192851886).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HandleTitleBarDoubleClick(): $CancellablePromise<void> {
    return $Call.ByID(3360874440);
}

export function HideMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(4289518733);
}

export function MinimizeMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(4039223773);
}

export function Next(): $CancellablePromise<void> {
    return $Call.ByID(3066213417);
}

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(3044086106);
}

export function Play(): $CancellablePromise<void> {
    return $Call.ByID(4192944954);
}

export function PollMediaAction(): $CancellablePromise<$models.PendingMediaAction> {
    return $Call.ByID(3358960897).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Previous(): $CancellablePromise<void> {
    return $Call.ByID(1860094781);
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(808738786);
}

export function RaiseWindow(): $CancellablePromise<void> {
    return $Call.ByID(2596737764);
}

export function RequestMainWindowClose(): $CancellablePromise<void> {
    return $Call.ByID(2929706724);
}

export function SaveGraphicsSettings(settings: $models.GraphicsSettings): $CancellablePromise<void> {
    return $Call.ByID(2641728101, settings);
}

export function SeekTo(positionMs: number): $CancellablePromise<void> {
    return $Call.ByID(1772558297, positionMs);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(21935507, app);
}

export function SetDataDir(dataDir: string): $CancellablePromise<void> {
    return $Call.ByID(2162564951, dataDir);
}

export function SetNativeTitleBarEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2066135357, enabled);
}

export function SetTaskbarIntegrationEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2068970037, enabled);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2175340530);
}

export function ToggleMaximizeMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(2817345855);
}

export function TogglePlayback(): $CancellablePromise<void> {
    return $Call.ByID(609116205);
}

export function UpdatePlayback(state: $models.PlaybackState): $CancellablePromise<void> {
    return $Call.ByID(2207095080, state);
}

// Private type creation functions
const $$createType0 = $models.GraphicsEnvironment.createFrom;
const $$createType1 = $models.PlaybackState.createFrom;
const $$createType2 = $models.PendingMediaAction.createFrom;
