// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pcmsink$0 from "../internal/pcmsink/models.js";

/**
 * AudioCapabilities describes native playback support on this host.
 */
export class AudioCapabilities {
    "nativeAvailable": boolean;
    "backend": string;
    "mpvAvailable": boolean;
    "vlcAvailable": boolean;
    "mpvLoadError"?: string;
    "initError"?: string;
    "pcmActive": boolean;
    "pcmError"?: string;
    "sinks"?: pcmsink$0.SinkStatus[];

    /** Creates a new AudioCapabilities instance. */
    constructor($$source: Partial<AudioCapabilities> = {}) {
        if (!("nativeAvailable" in $$source)) {
            this["nativeAvailable"] = false;
        }
        if (!("backend" in $$source)) {
            this["backend"] = "";
        }
        if (!("mpvAvailable" in $$source)) {
            this["mpvAvailable"] = false;
        }
        if (!("vlcAvailable" in $$source)) {
            this["vlcAvailable"] = false;
        }
        if (!("pcmActive" in $$source)) {
            this["pcmActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioCapabilities {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sinks" in $$parsedSource) {
            $$parsedSource["sinks"] = $$createField8_0($$parsedSource["sinks"]);
        }
        return new AudioCapabilities($$parsedSource as Partial<AudioCapabilities>);
    }
}

/**
 * AudioOutputConfig controls immersive / surround output for native backends.
 */
export class AudioOutputConfig {
    "mode": string;
    "exclusive": boolean;

    /**
     * Targets lists extra PCM outputs. Supported specs: "device", "stdout",
     * "fifo:<path>", "tcp:<host:port>", "tcp-listen:<addr>",
     * "unix:<path>", "unix-listen:<path>". When non-empty, mpv decodes to a
     * raw 48 kHz s16le stereo pipe and the audio fans out to every target.
     * Pipe targets require the mpv backend.
     */
    "targets"?: string[];

    /** Creates a new AudioOutputConfig instance. */
    constructor($$source: Partial<AudioOutputConfig> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("exclusive" in $$source)) {
            this["exclusive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioOutputConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioOutputConfig {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField2_0($$parsedSource["targets"]);
        }
        return new AudioOutputConfig($$parsedSource as Partial<AudioOutputConfig>);
    }
}

/**
 * AudioPlaybackState is polled by the frontend native engine.
 */
export class AudioPlaybackState {
    "currentTime": number;
    "duration": number;
    "playing": boolean;
    "ended": boolean;
    "error": string;

    /** Creates a new AudioPlaybackState instance. */
    constructor($$source: Partial<AudioPlaybackState> = {}) {
        if (!("currentTime" in $$source)) {
            this["currentTime"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("playing" in $$source)) {
            this["playing"] = false;
        }
        if (!("ended" in $$source)) {
            this["ended"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioPlaybackState instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioPlaybackState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioPlaybackState($$parsedSource as Partial<AudioPlaybackState>);
    }
}

/**
 * GraphicsEnvironment describes host graphics capabilities and active workarounds.
 */
export class GraphicsEnvironment {
    "supported": boolean;
    "platform": string;
    "wayland": boolean;
    "nvidia": boolean;
    "settings": GraphicsSettings;
    "defaults": GraphicsSettings;
    "appliedEnv": { [_ in string]?: string };
    "requiresRestart": boolean;
    "restartRequiredNote"?: string;

    /** Creates a new GraphicsEnvironment instance. */
    constructor($$source: Partial<GraphicsEnvironment> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("wayland" in $$source)) {
            this["wayland"] = false;
        }
        if (!("nvidia" in $$source)) {
            this["nvidia"] = false;
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new GraphicsSettings());
        }
        if (!("defaults" in $$source)) {
            this["defaults"] = (new GraphicsSettings());
        }
        if (!("appliedEnv" in $$source)) {
            this["appliedEnv"] = {};
        }
        if (!("requiresRestart" in $$source)) {
            this["requiresRestart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphicsEnvironment instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphicsEnvironment {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField4_0($$parsedSource["settings"]);
        }
        if ("defaults" in $$parsedSource) {
            $$parsedSource["defaults"] = $$createField5_0($$parsedSource["defaults"]);
        }
        if ("appliedEnv" in $$parsedSource) {
            $$parsedSource["appliedEnv"] = $$createField6_0($$parsedSource["appliedEnv"]);
        }
        return new GraphicsEnvironment($$parsedSource as Partial<GraphicsEnvironment>);
    }
}

/**
 * GraphicsSettings controls Linux WebKit/NVIDIA workarounds for the desktop app.
 */
export class GraphicsSettings {
    "disableDmabufRenderer": boolean;
    "disableCompositingMode": boolean;
    "nvDisableExplicitSync": string;

    /** Creates a new GraphicsSettings instance. */
    constructor($$source: Partial<GraphicsSettings> = {}) {
        if (!("disableDmabufRenderer" in $$source)) {
            this["disableDmabufRenderer"] = false;
        }
        if (!("disableCompositingMode" in $$source)) {
            this["disableCompositingMode"] = false;
        }
        if (!("nvDisableExplicitSync" in $$source)) {
            this["nvDisableExplicitSync"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphicsSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphicsSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphicsSettings($$parsedSource as Partial<GraphicsSettings>);
    }
}

export class PendingMediaAction {
    "action": string;
    "seekMs": number;
    "openUri": string;

    /** Creates a new PendingMediaAction instance. */
    constructor($$source: Partial<PendingMediaAction> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("seekMs" in $$source)) {
            this["seekMs"] = 0;
        }
        if (!("openUri" in $$source)) {
            this["openUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingMediaAction instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingMediaAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingMediaAction($$parsedSource as Partial<PendingMediaAction>);
    }
}

export class PlaybackState {
    "title": string;
    "artist": string;
    "album": string;
    "trackId": string;
    "coverArtId": string;
    "coverArtUrl": string;
    "durationMs": number;
    "positionMs": number;
    "playing": boolean;
    "canPlay": boolean;
    "canPause": boolean;
    "canGoNext": boolean;
    "canGoPrevious": boolean;

    /** Creates a new PlaybackState instance. */
    constructor($$source: Partial<PlaybackState> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("trackId" in $$source)) {
            this["trackId"] = "";
        }
        if (!("coverArtId" in $$source)) {
            this["coverArtId"] = "";
        }
        if (!("coverArtUrl" in $$source)) {
            this["coverArtUrl"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("positionMs" in $$source)) {
            this["positionMs"] = 0;
        }
        if (!("playing" in $$source)) {
            this["playing"] = false;
        }
        if (!("canPlay" in $$source)) {
            this["canPlay"] = false;
        }
        if (!("canPause" in $$source)) {
            this["canPause"] = false;
        }
        if (!("canGoNext" in $$source)) {
            this["canGoNext"] = false;
        }
        if (!("canGoPrevious" in $$source)) {
            this["canGoPrevious"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackState instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackState($$parsedSource as Partial<PlaybackState>);
    }
}

// Private type creation functions
const $$createType0 = pcmsink$0.SinkStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = GraphicsSettings.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
