// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService wraps the Wails in-app updater with Melovian's Atom-feed
 * provider. It is registered as a Wails service and also surfaced through
 * the HTTP API via desktop hooks, so the settings UI works identically in
 * desktop and server mode.
 * 
 * Auto-update is strictly opt-in: the periodic background check only runs
 * when the user has enabled it in settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * ApplyUpdate downloads, verifies, and stages the pending release. It runs
 * Check first if none is pending. Progress is observable through the
 * wails:updater:* events and GetStatus.
 */
export function ApplyUpdate(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3656438300).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckForUpdates runs a feed check and returns the resulting status.
 * Manual-only releases (installers, AppImage, containers) report
 * StatusManual with a releaseUrl the UI can open.
 */
export function CheckForUpdates(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2640647086).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAutoUpdate reports whether background auto-updates are enabled.
 */
export function GetAutoUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(1465334015);
}

/**
 * GetStatus returns the current updater state for polling UIs.
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1080117103).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RestartToApply relaunches into the staged update. The process exits.
 */
export function RestartToApply(): $CancellablePromise<void> {
    return $Call.ByID(371057625);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2123242760, app);
}

/**
 * SetAutoUpdate flips the opt-in flag and starts or stops the background
 * checker for the running session.
 */
export function SetAutoUpdate(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1943001131, enabled);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
